In [1]:
import pandas as pd

from ddeserts.annotate import add_all_stat_columns
from ddeserts.annotate import add_geo_columns
from ddeserts.annotate import with_columns_sorted
from ddeserts.load import load_cvap_data
from ddeserts.load import load_charter_cities

In [2]:
# load the data
pre_filter = lambda line: ('California' in line and 'CDP' not in line)

df = load_cvap_data('Place', pre_filter=pre_filter)
len(df)

485

In [3]:
# add geo columns and post-filter
add_geo_columns(df)
df = df[(df['state'] == 'California') & df['geotype'].isin(['city', 'town'])]
len(df)

482

In [4]:
# add charter city data
charter_cities = load_charter_cities()
df['hascharter'] = df['name'].isin(charter_cities)

In [5]:
# add stat columns and sort
add_all_stat_columns(df)
df = with_columns_sorted(df)
df

                      geoid                        geoname geotype  \
table line
Place 25130  16000US0600296      Adelanto city, California    city
      25156  16000US0600394  Agoura Hills city, California    city
      25221  16000US0600562       Alameda city, California    city
      25247  16000US0600674        Albany city, California    city
      25286  16000US0600884      Alhambra city, California    city
...                     ...                            ...     ...
      44786  16000US0686930    Yountville city, California    city
      44799  16000US0686944         Yreka city, California    city
      44812  16000US0686972     Yuba City city, California    city
      44825  16000US0687042       Yucaipa city, California    city
      44838  16000US0687056  Yucca Valley town, California    town

             hascharter          name       state  adu_est  adu_moe  cit_est  \
table line
Place 25130        True      Adelanto  California    21995      653    29610
      25156       False  Agoura Hills  California    16140      393    19320
      25221        True       Alameda  California    62565      524    72155
      25247        True        Albany  California    14665      241    16290
      25286        True      Alhambra  California    70315      496    69830
...                 ...           ...         ...      ...      ...      ...
      44786       False    Yountville  California     2760       81     2940
      44799       False         Yreka  California     5660      180     7500
      44812       False     Yuba City  California    49455      404    58480
      44825       False       Yucaipa  California    40175      646    50875
      44838       False  Yucca Valley  California    16730      502    21165

             cit_moe  ...  wht_adu_est  wht_adu_moe  wht_cit_est  wht_cit_moe  \
table line            ...
Place 25130      532  ...         3025          507         4025          852
      25156      468  ...        12585          479        14915          670
      25221      810  ...        28340         1043        32460         1204
      25247      629  ...         6790          434         8305          572
      25286      975  ...         6905          546         7230          550
...              ...  ...          ...          ...          ...          ...
      44786       41  ...         2140          198         2165          219
      44799      107  ...         4370          187         5360          293
      44812      771  ...        22890          587        28055          768
      44825      470  ...        24300         1143        31180         1347
      44838      199  ...        11440          896        14215         1178

             wht_cvap_est  wht_cvap_moe  wht_tot_est  wht_tot_moe  \
table line
Place 25130          2980           505         4070          854
      25156         12145           470        15355          631
      25221         27015          1001        33830         1232
      25247          6360           458         8800          568
      25286          6665           530         7500          569
...                   ...           ...          ...          ...
      44786          2105           197         2200          220
      44799          4345           186         5385          294
      44812         22700           614        28290          740
      44825         24025          1130        31455         1363
      44838         11345           891        14310         1182

             p_adu_dvap_est  p_adu_dvap_moe
table line
Place 25130        0.177540        0.062368
      25156        0.067534        0.054833
      25221        0.095740        0.021032
      25247        0.208660        0.050521
      25286        0.194411        0.019014
...                     ...             ...
      44786        0.016304        0.059021
      44799        0.011484        0.061461
      44812        0.152967        0.021981
      44825        0.061605        0.034790
      44838        0.027197        0.061301

[482 rows x 74 columns]

In [6]:
df.to_csv('output/ca-cities.csv')